"""Unified language definition + source enumeration rules (spec §6.2, §6.3).

Before this module the suffix sets were duplicated in at least four places and
had drifted apart:

* ``tools/source_evidence.DEFAULT_SOURCE_GLOBS``
* ``tools/project_profile._source_file_count``
* ``orchestrator/stages.run_s1`` (``_src_exts``)
* ``analysis`` (this package)

Every one of them now derives from :data:`LANGUAGE_SUFFIXES` here, so a new
language is added once.

Ambiguous suffixes
------------------
``.h`` is declared by both ``c`` and ``objective-c`` in the spec.  Resolution is
*first declaration wins* (see :func:`suffix_owner_language`), so ``.h`` maps to
``c`` -- the C/C++ header reading, which is the only defensible default for a
suffix whose contents are overwhelmingly C preprocessor + prototypes.  An
Objective-C header is still enumerated (the suffix is in the map); only its
*label* is conservative.  Override with :func:`set_ambiguous_suffix_owner` when a
target genuinely is Objective-C-dominant.

Enumeration contract (spec §18 Phase 1)
---------------------------------------
Exclusion is **never silent**.  :func:`scan_tree` does not descend into an
excluded directory, but it returns one :class:`ExcludedDir` record per excluded
directory carrying the file count inside it, so the coverage report can show what
was dropped and a reviewer can catch an over-broad exclusion (e.g. a project
whose real source lives under ``target/``).
"""

from __future__ import annotations

import os
import math
import subprocess
import time
from dataclasses import dataclass, field, replace
from pathlib import Path
from typing import (Any, Callable, Dict, Iterable, Iterator, List, MutableMapping,
                    Optional, Sequence, Set, Tuple)

# --- spec §6.3 -------------------------------------------------------------
#: Canonical suffix -> language table.  Order matters: the first language that
#: declares a suffix owns it (see module docstring).
LANGUAGE_SUFFIXES: Dict[str, List[str]] = {
    "java": [".java"],
    "kotlin": [".kt", ".kts"],
    "scala": [".scala"],
    "clojure": [".clj", ".cljc", ".cljs"],
    "python": [".py"],
    "go": [".go"],
    "javascript": [".js", ".jsx", ".mjs", ".cjs"],
    "typescript": [".ts", ".tsx"],
    "ruby": [".rb"],
    "php": [".php"],
    "rust": [".rs"],
    "c": [".c", ".h"],
    "cpp": [".cpp", ".cc", ".cxx", ".hpp", ".hh"],
    "csharp": [".cs"],
    "swift": [".swift"],
    "objective-c": [".m", ".mm", ".h"],
}

#: Explicit overrides for suffixes declared by more than one language.
AMBIGUOUS_SUFFIX_OWNER: Dict[str, str] = {
    ".h": "c",
}

#: JVM languages -- used by adapters that must pick a Java-family parser.
JVM_LANGUAGES: Tuple[str, ...] = ("java", "kotlin", "scala", "clojure")

# --- spec §6.2 -------------------------------------------------------------
#: Directories never scanned by default.  Overridable per target through
#: :class:`SourceFilter`; every skip is recorded so nothing is dropped silently.
DEFAULT_EXCLUDE_DIRS: Tuple[str, ...] = (
    ".git",
    "node_modules",
    "vendor",
    "dist",
    "build",
    "target",
    ".gradle",
    ".idea",
    "coverage",
    "__pycache__",
    ".generated",
    "generated",
    "third_party",
    # Large fuzz/test corpora contain data files, not implementation sources.
    # Record them as explicit exclusions instead of walking millions of inputs.
    "testdata",
    "test_data",
    "test_corpus",
    "fuzz_corpus",
    "fuzz_corpora",
    "wasm_corpus",
)

#: Extra build/tooling directories excluded on top of :data:`DEFAULT_EXCLUDE_DIRS`.
EXTRA_EXCLUDE_DIRS: Tuple[str, ...] = (
    ".venv",
    "venv",
    ".tox",
    ".mypy_cache",
    ".pytest_cache",
    ".ruff_cache",
    ".cache",
    ".next",
    ".nuxt",
    "out",
    "bin",
    "obj",
    "Pods",
    "DerivedData",
    ".svn",
    ".hg",
    "site-packages",
    "bower_components",
    ".terraform",
)

GENERATED_PATH_MARKERS: Tuple[str, ...] = (
    "/generated/", "/gen/", "/auto-generated/", "/autogen/",
)
GENERATED_NAME_MARKERS: Tuple[str, ...] = (
    ".generated.", ".g.dart", ".pb.go", "_pb2.py", "_pb2_grpc.py",
    ".designer.cs", ".min.js", ".min.css", ".bundle.js", ".chunk.js",
)
GENERATED_HEADER_MARKERS: Tuple[str, ...] = (
    "do not edit", "don't edit", "@generated", "auto-generated",
    "autogenerated", "generated by", "this file was generated",
    "machine generated",
)
VENDOR_PATH_MARKERS: Tuple[str, ...] = (
    "/vendor/", "/third_party/", "/3rdparty/", "/node_modules/",
    "/external/", "/extern/", "/deps/", "/contrib/", "/site-packages/",
)
TEST_PATH_MARKERS: Tuple[str, ...] = (
    "/test/", "/tests/", "/testing/", "/__tests__/", "/spec/", "/specs/",
    "/testdata/", "/fixtures/", "/test_data/",
)
TEST_NAME_SUFFIXES: Tuple[str, ...] = (
    ".test.js", ".test.jsx", ".test.ts", ".test.tsx", ".test.mjs",
    ".spec.js", ".spec.jsx", ".spec.ts", ".spec.tsx",
    "_test.go", "_test.py", "_test.rb", "_spec.rb",
    "test.java", "tests.java", "test.kt", "test.scala", "test.clj",
    "test.py", "test.go", "test.rb", "test.php", "test.cs", "test.swift",
)
TEST_FILE_NAMES: Tuple[str, ...] = (
    "conftest.py", "tests.py", "test.py", "test.go",
)

#: Hard cap on how many files are counted *inside* an excluded directory.  The
#: count only exists to make the exclusion auditable; it must never become a
#: second recursive audit of e.g. node_modules or a fuzz corpus.
MAX_EXCLUDED_DIR_SCAN = 2_048
DEFAULT_SCAN_TIMEOUT_SECONDS = 600
SOURCE_INVENTORY_POLICY_VERSION = "git-index-bounded-v1"


class SourceScanTimeout(RuntimeError):
    """Raised when a bounded source scan exceeds its wall-clock budget."""

    def __init__(self, progress: Dict[str, Any]):
        self.progress = dict(progress)
        super().__init__(
            "source scan incomplete after %.1fs (%d files seen, %d source files, "
            "%d directories; last path: %s)" % (
                float(progress.get("elapsed_seconds", 0)),
                int(progress.get("files_seen", 0)),
                int(progress.get("source_files", 0)),
                int(progress.get("directories_seen", 0)),
                str(progress.get("current_path") or "unknown")))


def register_language(language: str, suffixes: Sequence[str]) -> None:
    """Add/extend a language at runtime (keeps the single source of truth)."""
    entry = LANGUAGE_SUFFIXES.setdefault(language, [])
    for suffix in suffixes:
        suffix = suffix.lower()
        if suffix not in entry:
            entry.append(suffix)
    _rebuild_indexes()


def set_ambiguous_suffix_owner(suffix: str, language: str) -> None:
    """Force ``suffix`` to resolve to ``language`` (e.g. ``.h`` -> objective-c)."""
    AMBIGUOUS_SUFFIX_OWNER[suffix.lower()] = language
    _rebuild_indexes()


def _build_indexes() -> Tuple[Dict[str, str], Tuple[str, ...]]:
    mapping: Dict[str, str] = {}
    for language, suffixes in LANGUAGE_SUFFIXES.items():
        for suffix in suffixes:
            mapping.setdefault(suffix, language)
    for suffix, language in AMBIGUOUS_SUFFIX_OWNER.items():
        if suffix in mapping:
            mapping[suffix] = language
    ordered = tuple(sorted(
        {s for suffixes in LANGUAGE_SUFFIXES.values() for s in suffixes},
        key=lambda s: (len(s), s)))
    return mapping, ordered


SUFFIX_TO_LANGUAGE: Dict[str, str] = {}
ALL_SUFFIXES: Tuple[str, ...] = ()


def _rebuild_indexes() -> None:
    global SUFFIX_TO_LANGUAGE, ALL_SUFFIXES
    SUFFIX_TO_LANGUAGE, ALL_SUFFIXES = _build_indexes()


_rebuild_indexes()


def suffix_owner_language(path: "str | Path") -> Optional[str]:
    """Return the language owning ``path``'s suffix, or ``None``."""
    suffix = Path(str(path)).suffix.lower()
    return SUFFIX_TO_LANGUAGE.get(suffix)


# Back-compat alias -- ``analysis`` callers use the short name.
language_for = suffix_owner_language


def is_source_path(path: "str | Path") -> bool:
    return suffix_owner_language(path) is not None


def source_globs(languages: Optional[Iterable[str]] = None,
                 extra_suffixes: Optional[Iterable[str]] = None) -> List[str]:
    """Return ``rg``-style ``*.ext`` globs for the requested languages.

    ``languages=None`` means every registered language.  ``extra_suffixes``
    appends non-registered suffixes (target-specific extension).
    """
    if languages is None:
        suffixes = set(ALL_SUFFIXES)
    else:
        suffixes = set()
        for language in languages:
            suffixes.update(LANGUAGE_SUFFIXES.get(language, []))
    suffixes.update(extra_suffixes or [])
    return ["*%s" % s for s in sorted(suffixes, key=lambda s: (len(s), s))]


# --- classification --------------------------------------------------------

_HEADER_SCAN_BYTES = 4096
#: How many of the leading lines are checked for a generated-file banner.  The
#: banner is always at the very top; scanning the whole 4 KB head misfires on
#: files that merely *document* the marker strings (this module is the first
#: such file -- its own marker table made it classify itself as generated).
_HEADER_SCAN_LINES = 12


@dataclass
class SourceFilter:
    """Per-target enumeration policy (configurable + overridable, spec §6.2)."""

    exclude_dirs: List[str] = field(default_factory=lambda: list(DEFAULT_EXCLUDE_DIRS))
    extra_exclude_dirs: List[str] = field(default_factory=lambda: list(EXTRA_EXCLUDE_DIRS))
    #: Directory names that must be scanned even if a default rule excludes
    #: them -- the escape hatch for projects whose real source is under e.g.
    #: ``target/`` or ``build/``.
    include_overrides: List[str] = field(default_factory=list)
    extra_suffixes: List[str] = field(default_factory=list)
    max_file_bytes: int = 4 * 1024 * 1024
    follow_symlinks: bool = False
    #: Wall-clock limit for directory enumeration. Zero disables it explicitly.
    scan_timeout_seconds: int = DEFAULT_SCAN_TIMEOUT_SECONDS
    #: Per-invocation stop-loss inherited from the enclosing audit round. This
    #: is runtime-only and deliberately excluded from the persisted scope.
    runtime_deadline_override_seconds: Optional[float] = field(
        default=None, repr=False, compare=False)

    def effective_excludes(self) -> Tuple[str, ...]:
        names = list(self.exclude_dirs) + list(self.extra_exclude_dirs)
        overrides = {o.strip("/") for o in self.include_overrides}
        ordered: List[str] = []
        for name in names:
            if name in overrides or name in ordered:
                continue
            ordered.append(name)
        return tuple(ordered)

    def known_suffixes(self) -> Set[str]:
        return set(ALL_SUFFIXES) | {s.lower() for s in self.extra_suffixes}

    def as_dict(self) -> Dict[str, object]:
        return {
            "inventory_policy_version": SOURCE_INVENTORY_POLICY_VERSION,
            "exclude_dirs": list(self.effective_excludes()),
            "include_overrides": list(self.include_overrides),
            "extra_suffixes": list(self.extra_suffixes),
            "max_file_bytes": self.max_file_bytes,
            "follow_symlinks": self.follow_symlinks,
            "scan_timeout_seconds": self.scan_timeout_seconds,
        }


def _looks_generated(path: Path, rel: str) -> bool:
    lowered = rel.lower()
    name = path.name.lower()
    if any(marker in lowered for marker in GENERATED_PATH_MARKERS):
        return True
    if any(marker in name for marker in GENERATED_NAME_MARKERS):
        return True
    try:
        with path.open("r", encoding="utf-8", errors="replace") as fh:
            head = fh.read(_HEADER_SCAN_BYTES).lower()
    except OSError:
        return False
    return any(marker in head for marker in GENERATED_HEADER_MARKERS)


def _looks_vendor(rel: str) -> bool:
    lowered = "/%s" % rel.replace("\\", "/").lower().lstrip("/")
    return any(marker in lowered for marker in VENDOR_PATH_MARKERS)


def _looks_test(path: Path, rel: str) -> bool:
    lowered = "/%s" % rel.replace("\\", "/").lower().lstrip("/")
    name = path.name.lower()
    if name in TEST_FILE_NAMES:
        return True
    if any(marker in lowered for marker in TEST_PATH_MARKERS):
        return True
    if any(name.endswith(suffix) for suffix in TEST_NAME_SUFFIXES):
        return True
    if name.startswith("test_") or name.startswith("test-"):
        return True
    stem = name.rsplit(".", 1)[0] if "." in name else name
    if stem.endswith("test") or stem.endswith("tests") or stem.endswith("spec"):
        return True
    return False


def classify_file(rel_path: str, path: Optional[Path] = None) -> Dict[str, object]:
    """Classify one source file: production vs generated/vendor/test.

    Returns ``production`` / ``generated`` / ``vendor`` / ``test`` plus a
    human-readable ``reason``.  ``path`` enables content-based generated-file
    detection (header markers); without it only path/name rules apply.
    """
    probe = Path(str(rel_path).replace("\\", "/"))
    vendor = _looks_vendor(str(rel_path))
    test = _looks_test(probe, str(rel_path))
    path_generated = (any(m in str(rel_path).lower() for m in GENERATED_PATH_MARKERS)
                      or any(m in probe.name.lower() for m in GENERATED_NAME_MARKERS))
    # Test/vendor files are already excluded from production indexing. Avoid
    # opening each file just to collect an additional generated label.
    generated = (_looks_generated(probe, str(rel_path))
                 if path is not None and not (vendor or test)
                 else path_generated)
    reasons: List[str] = []
    if generated:
        reasons.append("generated")
    if vendor:
        reasons.append("vendor")
    if test:
        reasons.append("test")
    production = not (generated or vendor or test)
    if production:
        reasons.append("production")
    return {
        "production": production,
        "generated": generated,
        "vendor": vendor,
        "test": test,
        "reason": ",".join(reasons),
    }


# --- enumeration -----------------------------------------------------------

@dataclass
class ExcludedDir:
    """An excluded directory that was *not* descended into (auditability)."""

    rel_path: str
    reason: str
    file_count: int
    count_capped: bool = False
    producer: str = "walk"
    confidence: str = "exact"
    evidence_type: str = "static-observed"

    def as_dict(self) -> Dict[str, object]:
        return {
            "rel_path": self.rel_path,
            "reason": self.reason,
            "file_count": self.file_count,
            "count_capped": self.count_capped,
            "producer": self.producer,
            "confidence": self.confidence,
            "evidence_type": self.evidence_type,
        }


def _count_files(directory: Path, cap: int = MAX_EXCLUDED_DIR_SCAN,
                 follow_symlinks: bool = False,
                 deadline: Optional[float] = None) -> Tuple[int, bool]:
    total = 0
    visited = 0
    stack = [directory]
    while stack:
        current = stack.pop()
        try:
            entries = os.scandir(current)
        except OSError:
            continue
        with entries:
            for entry in entries:
                visited += 1
                if deadline is not None and time.monotonic() >= deadline:
                    raise TimeoutError("excluded directory counting exceeded scan budget")
                if entry.is_symlink() and not follow_symlinks:
                    continue
                try:
                    if entry.is_dir(follow_symlinks=follow_symlinks):
                        stack.append(Path(entry.path))
                    else:
                        total += 1
                except OSError:
                    continue
                if total >= cap:
                    return total, True
                if visited >= cap * 8:
                    return total, True
    return total, False


def resolve_source_dirs(root: Path, source_dirs: Optional[Sequence[str]] = None
                        ) -> Tuple[List[Path], List[str], List[Dict[str, str]]]:
    """Resolve the configured audit roots without silently widening scope.

    An omitted source-root list intentionally means the target root.  An
    *explicit* list that contains a typo or an outside path is different: the
    audit must retain that as a scope gap instead of falling back to the whole
    repository and making the resulting coverage look authoritative.

    Returns ``(bases, canonical_dirs, invalid_dirs)``.  ``canonical_dirs`` is
    rooted at ``root`` and suitable for a persisted scope contract; it is not a
    user-facing path echo and deliberately never includes outside paths.
    """
    root = Path(root).resolve()
    requested = list(source_dirs or [])
    if not requested:
        return [root], ["."], []

    bases: List[Path] = []
    canonical: List[str] = []
    invalid: List[Dict[str, str]] = []
    seen = set()
    for raw in requested:
        text = str(raw or "").strip()
        if not text:
            invalid.append({"path": text, "reason": "source-dir-missing"})
            continue
        try:
            candidate = (root / text).resolve()
            relative = candidate.relative_to(root).as_posix() or "."
        except (OSError, ValueError):
            invalid.append({"path": text, "reason": "source-dir-outside-root"})
            continue
        if not candidate.exists():
            invalid.append({"path": text, "reason": "source-dir-missing"})
            continue
        if relative in seen:
            continue
        seen.add(relative)
        bases.append(candidate)
        canonical.append(relative)
    bases.sort(key=lambda path: path.as_posix())
    canonical.sort()
    invalid.sort(key=lambda row: (row["path"], row["reason"]))
    return bases, canonical, invalid


def _git_index_files(root: Path, source_filter: SourceFilter,
                     source_dirs: Optional[Sequence[str]], source_only: bool,
                     stats: MutableMapping[str, Any],
                     progress_callback: Optional[Callable[[Dict[str, Any]], None]],
                     started: float, deadline: Optional[float]
                     ) -> Optional[Tuple[List[Tuple[Path, str]], List[ExcludedDir]]]:
    """Enumerate a Git working tree from its index, avoiding slow full walks.

    Tracked files, non-ignored untracked files, deletions, symlinks, and
    submodules are handled separately. A missing submodule is reported as a
    scope gap instead of silently disappearing from coverage.
    """
    root = root.resolve()

    def git(args: List[str]) -> Optional[bytes]:
        timeout = None if deadline is None else max(0.1, deadline - time.monotonic())
        try:
            result = subprocess.run(
                ["git", "-C", str(root)] + args,
                stdout=subprocess.PIPE, stderr=subprocess.DEVNULL,
                timeout=timeout, check=False)
        except (OSError, subprocess.TimeoutExpired):
            return None
        return result.stdout if result.returncode == 0 else None

    try:
        probe_timeout = (5.0 if deadline is None else
                         max(0.1, min(5.0, deadline - time.monotonic())))
        probe = subprocess.run(
            ["git", "-C", str(root), "rev-parse", "--show-toplevel"],
            stdout=subprocess.PIPE, stderr=subprocess.DEVNULL,
            timeout=probe_timeout, check=False)
    except (OSError, subprocess.TimeoutExpired):
        if deadline is not None and time.monotonic() >= deadline:
            raise SourceScanTimeout({
                "files_seen": 0, "source_files": 0, "directories_seen": 0,
                "elapsed_seconds": round(time.monotonic() - started, 3),
                "current_path": "git rev-parse",
            })
        return None
    if probe.returncode != 0:
        return None
    repo_root = Path(os.fsdecode(probe.stdout).strip()).resolve()
    try:
        repo_prefix = root.relative_to(repo_root).as_posix()
    except ValueError:
        return None
    if repo_prefix == ".":
        repo_prefix = ""
    prefix = repo_prefix + "/" if repo_prefix else ""
    _bases, canonical_dirs, invalid_dirs = resolve_source_dirs(root, source_dirs)
    if not canonical_dirs:
        stats.update({
            "files_seen": 0, "source_files": 0, "non_source_files": 0,
            "directories_seen": 0, "excluded_dirs_seen": 0,
            "elapsed_seconds": round(time.monotonic() - started, 3),
            "current_path": "", "git_index_used": True,
            "analysis_gaps": [row["reason"] for row in invalid_dirs],
            "gitlink_gaps": [],
        })
        return [], []
    allowed = ["" if item == "." else item.rstrip("/")
               for item in canonical_dirs]
    if not allowed:
        allowed = [""]
    exclusions = set(source_filter.effective_excludes())
    known_suffixes = source_filter.known_suffixes()
    stage_data = git(["ls-files", "--stage", "-z"])
    other_data = git(["ls-files", "--others", "--exclude-standard", "-z"])
    deleted_data = git(["ls-files", "--deleted", "-z"])
    if stage_data is None or other_data is None or deleted_data is None:
        if deadline is not None and time.monotonic() >= deadline:
            raise SourceScanTimeout({
                "files_seen": 0, "source_files": 0, "directories_seen": 0,
                "elapsed_seconds": round(time.monotonic() - started, 3),
                "current_path": "git ls-files",
            })
        return None
    def nul_records(data: bytes) -> Iterator[bytes]:
        """Yield NUL-delimited Git paths without allocating a giant split list."""
        offset = 0
        while offset < len(data):
            end = data.find(b"\0", offset)
            if end < 0:
                end = len(data)
            if end > offset:
                yield data[offset:end]
            offset = end + 1

    deleted = {os.fsdecode(item) for item in nul_records(deleted_data)}
    files: List[Tuple[Path, str]] = []
    excluded_counts: Dict[str, int] = {}
    excluded_capped: Set[str] = set()
    gaps: List[str] = []
    seen: Set[str] = set()
    state: Dict[str, Any] = {
        "files_seen": 0, "source_files": 0, "non_source_files": 0,
        "directories_seen": 0, "excluded_dirs_seen": 0,
        "elapsed_seconds": 0.0, "current_path": "git index",
        "git_index_used": True, "gitlink_gaps": [],
        "tracked_files": 0, "untracked_files": 0,
    }
    last_progress = started

    def tick(path: str = "git index", force: bool = False) -> None:
        nonlocal last_progress
        now = time.monotonic()
        state["elapsed_seconds"] = round(now - started, 3)
        if deadline is not None and now >= deadline:
            state["current_path"] = path
            stats.update(state)
            if progress_callback is not None:
                progress_callback(dict(state))
            raise SourceScanTimeout(state)
        if progress_callback is not None and (force or now - last_progress >= 10):
            state["current_path"] = path
            progress_callback(dict(state))
            last_progress = now

    def relative_path(repo_rel: str) -> Optional[str]:
        if prefix and not repo_rel.startswith(prefix):
            return None
        rel = repo_rel[len(prefix):] if prefix else repo_rel
        if not rel or rel == ".":
            return None
        if not any(not base or rel == base or rel.startswith(base + "/")
                   for base in allowed):
            return None
        return rel

    def excluded_parent(rel: str) -> Optional[str]:
        selected_base = max(
            (base for base in allowed
             if not base or rel == base or rel.startswith(base + "/")),
            key=len, default="")
        tail = rel[len(selected_base):].lstrip("/") if selected_base else rel
        parts = tail.split("/")
        for index, part in enumerate(parts[:-1]):
            if part in exclusions:
                excluded_tail = "/".join(parts[:index + 1])
                return (selected_base + "/" + excluded_tail
                        if selected_base else excluded_tail)
        return None

    def add_path(repo_rel: str, mode: str = "", tracked: bool = False) -> None:
        rel = relative_path(repo_rel)
        if rel is None or rel in seen:
            return
        parent_exclusion = (
            rel if mode in ("160000", "040000")
            and Path(rel).name in exclusions and rel not in allowed
            else excluded_parent(rel))
        if parent_exclusion:
            count = excluded_counts.get(parent_exclusion, 0)
            if count < MAX_EXCLUDED_DIR_SCAN:
                excluded_counts[parent_exclusion] = count + 1
            else:
                excluded_capped.add(parent_exclusion)
            return
        if repo_rel in deleted:
            return
        abs_path = repo_root / repo_rel
        if mode == "160000" or mode == "040000":
            if abs_path.is_dir():
                nested_filter = source_filter
                if deadline is not None:
                    remaining = deadline - time.monotonic()
                    if remaining <= 0:
                        tick(rel, force=True)
                    nested_filter = replace(
                        source_filter, scan_timeout_seconds=remaining)
                nested_stats: Dict[str, Any] = {}
                nested_files, nested_excluded = scan_tree(
                    abs_path, nested_filter, source_only=source_only,
                    stats=nested_stats, progress_callback=progress_callback)
                for nested_path, nested_rel in nested_files:
                    combined_rel = rel + "/" + nested_rel
                    if combined_rel not in seen:
                        seen.add(combined_rel)
                        files.append((nested_path, combined_rel))
                for row in nested_excluded:
                    excluded.append(ExcludedDir(
                        rel_path=rel + "/" + row.rel_path,
                        reason=row.reason, file_count=row.file_count,
                        count_capped=row.count_capped,
                        producer=row.producer, confidence=row.confidence,
                        evidence_type=row.evidence_type))
                for key in ("files_seen", "source_files", "non_source_files",
                            "directories_seen", "excluded_dirs_seen"):
                    state[key] += int(nested_stats.get(key, 0))
                gaps.extend(str(item) for item in nested_stats.get("gitlink_gaps", []))
                tick(rel)
            else:
                gap = "gitlink-content-unavailable:%s" % rel
                gaps.append(gap)
                excluded.append(ExcludedDir(
                    rel_path=rel, reason="gitlink-content-unavailable",
                    file_count=0, count_capped=True,
                    producer="git-index", confidence="lower-bound",
                    evidence_type="repository-metadata"))
            return
        if mode == "120000" or (not tracked and abs_path.is_symlink()):
            excluded.append(ExcludedDir(
                rel_path=rel, reason="symlink-not-followed", file_count=0,
                count_capped=False, producer="git-index",
                confidence="exact", evidence_type="repository-metadata"))
            return
        seen.add(rel)
        state["files_seen"] += 1
        if tracked:
            state["tracked_files"] += 1
        else:
            state["untracked_files"] += 1
        if Path(rel).suffix.lower() in known_suffixes:
            state["source_files"] += 1
            if not source_only:
                files.append((abs_path, rel))
            elif mode != "120000":
                files.append((abs_path, rel))
        else:
            state["non_source_files"] += 1
            if not source_only:
                files.append((abs_path, rel))

    for index, record in enumerate(nul_records(stage_data)):
        try:
            metadata, raw_path = record.split(b"\t", 1)
            mode = metadata.split(b" ", 1)[0].decode("ascii", errors="ignore")
            repo_rel = os.fsdecode(raw_path)
        except ValueError:
            continue
        add_path(repo_rel, mode, tracked=True)
        if index % 8192 == 0:
            tick(repo_rel)

    for index, raw_path in enumerate(nul_records(other_data)):
        repo_rel = os.fsdecode(raw_path)
        add_path(repo_rel, tracked=False)
        if index % 8192 == 0:
            tick(repo_rel)

    for rel, count in sorted(excluded_counts.items()):
        excluded.append(ExcludedDir(
            rel_path=rel, reason="excluded-dir:%s" % Path(rel).name,
            file_count=count, count_capped=rel in excluded_capped,
            producer="git-index", confidence="lower-bound",
            evidence_type="repository-metadata"))
    if invalid_dirs:
        state["analysis_gaps"] = [row["reason"] for row in invalid_dirs]
    state["gitlink_gaps"] = sorted(set(gaps))
    state["excluded_dirs_seen"] = len(excluded)
    state["elapsed_seconds"] = round(time.monotonic() - started, 3)
    tick(force=True)
    stats.update(state)
    files.sort(key=lambda item: item[1])
    excluded.sort(key=lambda item: item.rel_path)
    return files, excluded


def scan_tree(root: Path, source_filter: Optional[SourceFilter] = None,
              source_dirs: Optional[Sequence[str]] = None, *,
              source_only: bool = False,
              stats: Optional[MutableMapping[str, Any]] = None,
              progress_callback: Optional[Callable[[Dict[str, Any]], None]] = None
              ) -> Tuple[List[Tuple[Path, str]], List[ExcludedDir]]:
    """Enumerate every file under ``root`` (or ``source_dirs``), deterministically.

    Returns ``(files, excluded_dirs)`` where ``files`` is a sorted list of
    ``(absolute_path, root_relative_posix_path)``. ``source_only`` avoids
    retaining non-source paths in memory; their counts are returned through
    ``stats``. Source-like test/vendor/generated files remain in the list so
    each can keep its explicit skip reason.

    Excluded directories are not descended into; each contributes one
    :class:`ExcludedDir` record with its file count instead.
    """
    root = root.resolve()
    flt = source_filter or SourceFilter()
    exclusions = flt.effective_excludes()
    known_suffixes = flt.known_suffixes()
    started = time.monotonic()
    timeout = max(0.0, float(flt.scan_timeout_seconds or 0))
    if flt.runtime_deadline_override_seconds is not None:
        override = float(flt.runtime_deadline_override_seconds)
        if not math.isfinite(override) or override <= 0:
            raise ValueError("runtime source deadline must be a positive finite number")
        timeout = min(timeout, override) if timeout else override
    deadline = started + timeout if timeout else None
    state: Dict[str, Any] = {
        "files_seen": 0,
        "source_files": 0,
        "non_source_files": 0,
        "directories_seen": 0,
        "excluded_dirs_seen": 0,
        "elapsed_seconds": 0.0,
        "current_path": "",
        "git_index_used": False,
        "gitlink_gaps": [],
    }
    last_progress = started

    def checkpoint(path: Optional[Path] = None, force: bool = False) -> None:
        nonlocal last_progress
        now = time.monotonic()
        state["elapsed_seconds"] = round(now - started, 3)
        progress_due = force or (progress_callback is not None
                                 and now - last_progress >= 10)
        deadline_due = deadline is not None and now >= deadline
        if path is not None and (progress_due or deadline_due):
            try:
                state["current_path"] = path.relative_to(root).as_posix()
            except ValueError:
                state["current_path"] = str(path)
        if deadline_due:
            snapshot = dict(state)
            if progress_callback is not None:
                progress_callback(snapshot)
            if stats is not None:
                stats.update(snapshot)
            raise SourceScanTimeout(snapshot)
        if progress_callback is not None and progress_due:
            progress_callback(dict(state))
            last_progress = now

    def add_file(path: Path, rel: str) -> None:
        state["files_seen"] += 1
        is_source = Path(rel).suffix.lower() in known_suffixes
        if is_source:
            state["source_files"] += 1
        else:
            state["non_source_files"] += 1
        if not source_only or is_source:
            if rel not in seen_files:
                seen_files.add(rel)
                files.append((path, rel))

    bases, _canonical, _invalid = resolve_source_dirs(root, source_dirs)

    if not flt.follow_symlinks:
        git_inventory = _git_index_files(
            root, flt, source_dirs, source_only, state if stats is None else stats,
            progress_callback, started, deadline)
        if git_inventory is not None:
            return git_inventory

    files: List[Tuple[Path, str]] = []
    excluded: List[ExcludedDir] = []
    seen_files: Set[str] = set()
    seen_dirs: Set[str] = set()

    def rel_of(path: Path) -> Optional[str]:
        try:
            # The common no-symlink path needs no realpath/stat call for every
            # directory entry. When callers explicitly follow links, retain the
            # resolved containment check.
            candidate = path.resolve() if flt.follow_symlinks else path
            return candidate.relative_to(root).as_posix()
        except (OSError, ValueError):
            return None

    def walk(base: Path) -> None:
        if base.is_file():
            rel = rel_of(base)
            if rel:
                add_file(base, rel)
            return
        stack: List[Path] = [base]
        while stack:
            current = stack.pop()
            state["directories_seen"] += 1
            checkpoint(current)
            try:
                entries = os.scandir(current)
            except OSError:
                continue
            with entries:
                for entry in entries:
                    entry_path = Path(entry.path)
                    checkpoint(entry_path)
                    try:
                        is_symlink = entry.is_symlink()
                    except OSError:
                        continue
                    if is_symlink and not flt.follow_symlinks:
                        rel = rel_of(entry_path)
                        if rel and rel not in seen_dirs:
                            seen_dirs.add(rel)
                            state["excluded_dirs_seen"] += 1
                            excluded.append(ExcludedDir(
                                rel_path=rel, reason="symlink-not-followed",
                                file_count=0))
                        continue
                    try:
                        is_dir = entry.is_dir(follow_symlinks=flt.follow_symlinks)
                    except OSError:
                        continue
                    if is_dir:
                        rel = rel_of(entry_path)
                        if rel is None:
                            continue
                        if entry.name in exclusions:
                            if rel not in seen_dirs:
                                seen_dirs.add(rel)
                                try:
                                    count, capped = _count_files(
                                        entry_path,
                                        follow_symlinks=flt.follow_symlinks,
                                        deadline=deadline)
                                except TimeoutError:
                                    checkpoint(entry_path, force=True)
                                    raise
                                state["excluded_dirs_seen"] += 1
                                excluded.append(ExcludedDir(
                                    rel_path=rel, reason="excluded-dir:%s" % entry.name,
                                    file_count=count, count_capped=capped))
                            continue
                        stack.append(entry_path)
                    else:
                        rel = rel_of(entry_path)
                        if rel:
                            add_file(entry_path, rel)

    for base in sorted(bases, key=lambda p: str(p)):
        walk(base)

    checkpoint(force=True)
    if stats is not None:
        stats.update(state)
    files.sort(key=lambda item: item[1])
    excluded.sort(key=lambda item: item.rel_path)
    return files, excluded


def excluded_dir_reason(rel_path: str,
                        exclude_dirs: Sequence[str] = ()) -> Optional[str]:
    """Return the exclusion reason for ``rel_path``, or ``None`` if not excluded."""
    names = tuple(exclude_dirs) or (DEFAULT_EXCLUDE_DIRS + EXTRA_EXCLUDE_DIRS)
    parts = Path(str(rel_path).replace("\\", "/")).parts[:-1]
    for part in parts:
        if part in names:
            return "excluded-dir:%s" % part
    return None


def iter_source_files(root: Path, source_dirs: Optional[Sequence[str]] = None,
                      source_filter: Optional[SourceFilter] = None
                      ) -> Iterator[Tuple[Path, str]]:
    """Convenience generator over *source-suffix* files (excluded dirs skipped).

    Use :func:`scan_tree` when the exclusion trail matters; this helper is for
    callers that just want to iterate candidates.
    """
    flt = source_filter or SourceFilter()
    known = flt.known_suffixes()
    files, _excluded = scan_tree(root, flt, source_dirs, source_only=True)
    for path, rel in files:
        if Path(rel).suffix.lower() in known:
            yield path, rel


# --- shared file reading ---------------------------------------------------

DEFAULT_MAX_FILE_BYTES = 4 * 1024 * 1024


def read_source_lines(path, max_bytes: int = DEFAULT_MAX_FILE_BYTES,
                      ) -> Optional[List[str]]:
    """Read ``path`` as lines, or ``None`` when unreadable / over ``max_bytes``.

    ``None`` means "we could not read this", which the callers record as a
    ``skip_reason`` -- never as "the file has no content".
    """
    path = Path(path)
    try:
        if max_bytes and path.stat().st_size > max_bytes:
            return None
        return path.read_text(encoding="utf-8", errors="replace").splitlines()
    except OSError:
        return None
