"""Unified language definition + source enumeration rules (spec §6.2, §6.3).

Before this module the suffix sets were duplicated in at least four places and
had drifted apart:

* ``tools/source_evidence.DEFAULT_SOURCE_GLOBS``
* ``tools/project_profile._source_file_count``
* ``orchestrator/stages.run_s1`` (``_src_exts``)
* ``analysis`` (this package)

Every one of them now derives from :data:`LANGUAGE_SUFFIXES` here, so a new
language is added once.

Ambiguous suffixes
------------------
``.h`` is declared by both ``c`` and ``objective-c`` in the spec.  Resolution is
*first declaration wins* (see :func:`suffix_owner_language`), so ``.h`` maps to
``c`` -- the C/C++ header reading, which is the only defensible default for a
suffix whose contents are overwhelmingly C preprocessor + prototypes.  An
Objective-C header is still enumerated (the suffix is in the map); only its
*label* is conservative.  Override with :func:`set_ambiguous_suffix_owner` when a
target genuinely is Objective-C-dominant.

Enumeration contract (spec §18 Phase 1)
---------------------------------------
Exclusion is **never silent**.  :func:`scan_tree` does not descend into an
excluded directory, but it returns one :class:`ExcludedDir` record per excluded
directory carrying the file count inside it, so the coverage report can show what
was dropped and a reviewer can catch an over-broad exclusion (e.g. a project
whose real source lives under ``target/``).
"""

from __future__ import annotations

import os
from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, Iterable, Iterator, List, Optional, Sequence, Set, Tuple

# --- spec §6.3 -------------------------------------------------------------
#: Canonical suffix -> language table.  Order matters: the first language that
#: declares a suffix owns it (see module docstring).
LANGUAGE_SUFFIXES: Dict[str, List[str]] = {
    "java": [".java"],
    "kotlin": [".kt", ".kts"],
    "scala": [".scala"],
    "clojure": [".clj", ".cljc", ".cljs"],
    "python": [".py"],
    "go": [".go"],
    "javascript": [".js", ".jsx", ".mjs", ".cjs"],
    "typescript": [".ts", ".tsx"],
    "ruby": [".rb"],
    "php": [".php"],
    "rust": [".rs"],
    "c": [".c", ".h"],
    "cpp": [".cpp", ".cc", ".cxx", ".hpp", ".hh"],
    "csharp": [".cs"],
    "swift": [".swift"],
    "objective-c": [".m", ".mm", ".h"],
}

#: Explicit overrides for suffixes declared by more than one language.
AMBIGUOUS_SUFFIX_OWNER: Dict[str, str] = {
    ".h": "c",
}

#: JVM languages -- used by adapters that must pick a Java-family parser.
JVM_LANGUAGES: Tuple[str, ...] = ("java", "kotlin", "scala", "clojure")

# --- spec §6.2 -------------------------------------------------------------
#: Directories never scanned by default.  Overridable per target through
#: :class:`SourceFilter`; every skip is recorded so nothing is dropped silently.
DEFAULT_EXCLUDE_DIRS: Tuple[str, ...] = (
    ".git",
    "node_modules",
    "vendor",
    "dist",
    "build",
    "target",
    ".gradle",
    ".idea",
    "coverage",
    "__pycache__",
    ".generated",
    "generated",
    "third_party",
)

#: Extra build/tooling directories excluded on top of :data:`DEFAULT_EXCLUDE_DIRS`.
EXTRA_EXCLUDE_DIRS: Tuple[str, ...] = (
    ".venv",
    "venv",
    ".tox",
    ".mypy_cache",
    ".pytest_cache",
    ".ruff_cache",
    ".cache",
    ".next",
    ".nuxt",
    "out",
    "bin",
    "obj",
    "Pods",
    "DerivedData",
    ".svn",
    ".hg",
    "site-packages",
    "bower_components",
    ".terraform",
)

GENERATED_PATH_MARKERS: Tuple[str, ...] = (
    "/generated/", "/gen/", "/auto-generated/", "/autogen/",
)
GENERATED_NAME_MARKERS: Tuple[str, ...] = (
    ".generated.", ".g.dart", ".pb.go", "_pb2.py", "_pb2_grpc.py",
    ".designer.cs", ".min.js", ".min.css", ".bundle.js", ".chunk.js",
)
GENERATED_HEADER_MARKERS: Tuple[str, ...] = (
    "do not edit", "don't edit", "@generated", "auto-generated",
    "autogenerated", "generated by", "this file was generated",
    "machine generated",
)
VENDOR_PATH_MARKERS: Tuple[str, ...] = (
    "/vendor/", "/third_party/", "/3rdparty/", "/node_modules/",
    "/external/", "/extern/", "/deps/", "/contrib/", "/site-packages/",
)
TEST_PATH_MARKERS: Tuple[str, ...] = (
    "/test/", "/tests/", "/testing/", "/__tests__/", "/spec/", "/specs/",
    "/testdata/", "/fixtures/", "/test_data/",
)
TEST_NAME_SUFFIXES: Tuple[str, ...] = (
    ".test.js", ".test.jsx", ".test.ts", ".test.tsx", ".test.mjs",
    ".spec.js", ".spec.jsx", ".spec.ts", ".spec.tsx",
    "_test.go", "_test.py", "_test.rb", "_spec.rb",
    "test.java", "tests.java", "test.kt", "test.scala", "test.clj",
    "test.py", "test.go", "test.rb", "test.php", "test.cs", "test.swift",
)
TEST_FILE_NAMES: Tuple[str, ...] = (
    "conftest.py", "tests.py", "test.py", "test.go",
)

#: Hard cap on how many files are counted *inside* an excluded directory.  The
#: count only exists to make the exclusion auditable; it must never make a scan
#: of e.g. node_modules unbounded.  ``ExcludedDir.count_capped`` records the cap.
MAX_EXCLUDED_DIR_SCAN = 50_000


def register_language(language: str, suffixes: Sequence[str]) -> None:
    """Add/extend a language at runtime (keeps the single source of truth)."""
    entry = LANGUAGE_SUFFIXES.setdefault(language, [])
    for suffix in suffixes:
        suffix = suffix.lower()
        if suffix not in entry:
            entry.append(suffix)
    _rebuild_indexes()


def set_ambiguous_suffix_owner(suffix: str, language: str) -> None:
    """Force ``suffix`` to resolve to ``language`` (e.g. ``.h`` -> objective-c)."""
    AMBIGUOUS_SUFFIX_OWNER[suffix.lower()] = language
    _rebuild_indexes()


def _build_indexes() -> Tuple[Dict[str, str], Tuple[str, ...]]:
    mapping: Dict[str, str] = {}
    for language, suffixes in LANGUAGE_SUFFIXES.items():
        for suffix in suffixes:
            mapping.setdefault(suffix, language)
    for suffix, language in AMBIGUOUS_SUFFIX_OWNER.items():
        if suffix in mapping:
            mapping[suffix] = language
    ordered = tuple(sorted(
        {s for suffixes in LANGUAGE_SUFFIXES.values() for s in suffixes},
        key=lambda s: (len(s), s)))
    return mapping, ordered


SUFFIX_TO_LANGUAGE: Dict[str, str] = {}
ALL_SUFFIXES: Tuple[str, ...] = ()


def _rebuild_indexes() -> None:
    global SUFFIX_TO_LANGUAGE, ALL_SUFFIXES
    SUFFIX_TO_LANGUAGE, ALL_SUFFIXES = _build_indexes()


_rebuild_indexes()


def suffix_owner_language(path: "str | Path") -> Optional[str]:
    """Return the language owning ``path``'s suffix, or ``None``."""
    suffix = Path(str(path)).suffix.lower()
    return SUFFIX_TO_LANGUAGE.get(suffix)


# Back-compat alias -- ``analysis`` callers use the short name.
language_for = suffix_owner_language


def is_source_path(path: "str | Path") -> bool:
    return suffix_owner_language(path) is not None


def source_globs(languages: Optional[Iterable[str]] = None,
                 extra_suffixes: Optional[Iterable[str]] = None) -> List[str]:
    """Return ``rg``-style ``*.ext`` globs for the requested languages.

    ``languages=None`` means every registered language.  ``extra_suffixes``
    appends non-registered suffixes (target-specific extension).
    """
    if languages is None:
        suffixes = set(ALL_SUFFIXES)
    else:
        suffixes = set()
        for language in languages:
            suffixes.update(LANGUAGE_SUFFIXES.get(language, []))
    suffixes.update(extra_suffixes or [])
    return ["*%s" % s for s in sorted(suffixes, key=lambda s: (len(s), s))]


# --- classification --------------------------------------------------------

_HEADER_SCAN_BYTES = 4096
#: How many of the leading lines are checked for a generated-file banner.  The
#: banner is always at the very top; scanning the whole 4 KB head misfires on
#: files that merely *document* the marker strings (this module is the first
#: such file -- its own marker table made it classify itself as generated).
_HEADER_SCAN_LINES = 12


@dataclass
class SourceFilter:
    """Per-target enumeration policy (configurable + overridable, spec §6.2)."""

    exclude_dirs: List[str] = field(default_factory=lambda: list(DEFAULT_EXCLUDE_DIRS))
    extra_exclude_dirs: List[str] = field(default_factory=lambda: list(EXTRA_EXCLUDE_DIRS))
    #: Directory names that must be scanned even if a default rule excludes
    #: them -- the escape hatch for projects whose real source is under e.g.
    #: ``target/`` or ``build/``.
    include_overrides: List[str] = field(default_factory=list)
    extra_suffixes: List[str] = field(default_factory=list)
    max_file_bytes: int = 4 * 1024 * 1024
    follow_symlinks: bool = False

    def effective_excludes(self) -> Tuple[str, ...]:
        names = list(self.exclude_dirs) + list(self.extra_exclude_dirs)
        overrides = {o.strip("/") for o in self.include_overrides}
        ordered: List[str] = []
        for name in names:
            if name in overrides or name in ordered:
                continue
            ordered.append(name)
        return tuple(ordered)

    def known_suffixes(self) -> Set[str]:
        return set(ALL_SUFFIXES) | {s.lower() for s in self.extra_suffixes}

    def as_dict(self) -> Dict[str, object]:
        return {
            "exclude_dirs": list(self.effective_excludes()),
            "include_overrides": list(self.include_overrides),
            "extra_suffixes": list(self.extra_suffixes),
            "max_file_bytes": self.max_file_bytes,
            "follow_symlinks": self.follow_symlinks,
        }


def _looks_generated(path: Path, rel: str) -> bool:
    lowered = rel.lower()
    name = path.name.lower()
    if any(marker in lowered for marker in GENERATED_PATH_MARKERS):
        return True
    if any(marker in name for marker in GENERATED_NAME_MARKERS):
        return True
    try:
        with path.open("r", encoding="utf-8", errors="replace") as fh:
            head = fh.read(_HEADER_SCAN_BYTES).lower()
    except OSError:
        return False
    return any(marker in head for marker in GENERATED_HEADER_MARKERS)


def _looks_vendor(rel: str) -> bool:
    lowered = "/%s" % rel.replace("\\", "/").lower().lstrip("/")
    return any(marker in lowered for marker in VENDOR_PATH_MARKERS)


def _looks_test(path: Path, rel: str) -> bool:
    lowered = "/%s" % rel.replace("\\", "/").lower().lstrip("/")
    name = path.name.lower()
    if name in TEST_FILE_NAMES:
        return True
    if any(marker in lowered for marker in TEST_PATH_MARKERS):
        return True
    if any(name.endswith(suffix) for suffix in TEST_NAME_SUFFIXES):
        return True
    if name.startswith("test_") or name.startswith("test-"):
        return True
    stem = name.rsplit(".", 1)[0] if "." in name else name
    if stem.endswith("test") or stem.endswith("tests") or stem.endswith("spec"):
        return True
    return False


def classify_file(rel_path: str, path: Optional[Path] = None) -> Dict[str, object]:
    """Classify one source file: production vs generated/vendor/test.

    Returns ``production`` / ``generated`` / ``vendor`` / ``test`` plus a
    human-readable ``reason``.  ``path`` enables content-based generated-file
    detection (header markers); without it only path/name rules apply.
    """
    probe = Path(str(rel_path).replace("\\", "/"))
    generated = _looks_generated(probe, str(rel_path)) if path is not None \
        else (any(m in str(rel_path).lower() for m in GENERATED_PATH_MARKERS)
              or any(m in probe.name.lower() for m in GENERATED_NAME_MARKERS))
    vendor = _looks_vendor(str(rel_path))
    test = _looks_test(probe, str(rel_path))
    reasons: List[str] = []
    if generated:
        reasons.append("generated")
    if vendor:
        reasons.append("vendor")
    if test:
        reasons.append("test")
    production = not (generated or vendor or test)
    if production:
        reasons.append("production")
    return {
        "production": production,
        "generated": generated,
        "vendor": vendor,
        "test": test,
        "reason": ",".join(reasons),
    }


# --- enumeration -----------------------------------------------------------

@dataclass
class ExcludedDir:
    """An excluded directory that was *not* descended into (auditability)."""

    rel_path: str
    reason: str
    file_count: int
    count_capped: bool = False
    producer: str = "walk"
    confidence: str = "exact"
    evidence_type: str = "static-observed"

    def as_dict(self) -> Dict[str, object]:
        return {
            "rel_path": self.rel_path,
            "reason": self.reason,
            "file_count": self.file_count,
            "count_capped": self.count_capped,
            "producer": self.producer,
            "confidence": self.confidence,
            "evidence_type": self.evidence_type,
        }


def _count_files(directory: Path, cap: int = MAX_EXCLUDED_DIR_SCAN,
                 follow_symlinks: bool = False) -> Tuple[int, bool]:
    total = 0
    stack = [directory]
    while stack:
        current = stack.pop()
        try:
            entries = list(os.scandir(current))
        except OSError:
            continue
        for entry in entries:
            if entry.is_symlink() and not follow_symlinks:
                continue
            try:
                if entry.is_dir(follow_symlinks=follow_symlinks):
                    stack.append(Path(entry.path))
                else:
                    total += 1
            except OSError:
                continue
            if total >= cap:
                return total, True
    return total, False


def scan_tree(root: Path, source_filter: Optional[SourceFilter] = None,
              source_dirs: Optional[Sequence[str]] = None
              ) -> Tuple[List[Tuple[Path, str]], List[ExcludedDir]]:
    """Enumerate every file under ``root`` (or ``source_dirs``), deterministically.

    Returns ``(files, excluded_dirs)`` where ``files`` is a sorted list of
    ``(absolute_path, root_relative_posix_path)`` for *all* files, including
    those that will later be classified as generated/vendor/test or dropped for
    a non-source suffix.  Nothing is filtered here -- the inventory needs the
    complete universe so it can attach a ``skip_reason`` to every entry.

    Excluded directories are not descended into; each contributes one
    :class:`ExcludedDir` record with its file count instead.
    """
    root = root.resolve()
    flt = source_filter or SourceFilter()
    exclusions = flt.effective_excludes()

    if source_dirs:
        bases: List[Path] = []
        for rel in source_dirs:
            candidate = (root / str(rel)).resolve()
            if candidate.exists() and (str(candidate) == str(root)
                                       or str(candidate).startswith(str(root) + os.sep)):
                bases.append(candidate)
        if not bases:
            _files, excluded = scan_tree(root, flt, None)
            return _files, excluded
    else:
        bases = [root]

    files: List[Tuple[Path, str]] = []
    excluded: List[ExcludedDir] = []
    seen_files: Set[str] = set()
    seen_dirs: Set[str] = set()

    def rel_of(path: Path) -> Optional[str]:
        try:
            return path.resolve().relative_to(root).as_posix()
        except ValueError:
            return None

    def walk(base: Path) -> None:
        if base.is_file():
            rel = rel_of(base)
            if rel and rel not in seen_files:
                seen_files.add(rel)
                files.append((base, rel))
            return
        stack: List[Path] = [base]
        while stack:
            current = stack.pop()
            try:
                with os.scandir(current) as it:
                    entries = sorted(it, key=lambda e: e.name)
            except OSError:
                continue
            for entry in entries:
                entry_path = Path(entry.path)
                is_symlink = entry.is_symlink()
                if is_symlink and not flt.follow_symlinks:
                    rel = rel_of(entry_path)
                    if rel and rel not in seen_dirs:
                        seen_dirs.add(rel)
                        excluded.append(ExcludedDir(
                            rel_path=rel, reason="symlink-not-followed",
                            file_count=0))
                    continue
                try:
                    is_dir = entry.is_dir(follow_symlinks=flt.follow_symlinks)
                except OSError:
                    continue
                if is_dir:
                    rel = rel_of(entry_path)
                    if rel is None:
                        continue
                    if entry.name in exclusions:
                        if rel not in seen_dirs:
                            seen_dirs.add(rel)
                            count, capped = _count_files(
                                entry_path, follow_symlinks=flt.follow_symlinks)
                            excluded.append(ExcludedDir(
                                rel_path=rel, reason="excluded-dir:%s" % entry.name,
                                file_count=count, count_capped=capped))
                        continue
                    stack.append(entry_path)
                else:
                    rel = rel_of(entry_path)
                    if rel and rel not in seen_files:
                        seen_files.add(rel)
                        files.append((entry_path, rel))

    for base in sorted(bases, key=lambda p: str(p)):
        walk(base)

    files.sort(key=lambda item: item[1])
    excluded.sort(key=lambda item: item.rel_path)
    return files, excluded


def excluded_dir_reason(rel_path: str,
                        exclude_dirs: Sequence[str] = ()) -> Optional[str]:
    """Return the exclusion reason for ``rel_path``, or ``None`` if not excluded."""
    names = tuple(exclude_dirs) or (DEFAULT_EXCLUDE_DIRS + EXTRA_EXCLUDE_DIRS)
    parts = Path(str(rel_path).replace("\\", "/")).parts[:-1]
    for part in parts:
        if part in names:
            return "excluded-dir:%s" % part
    return None


def iter_source_files(root: Path, source_dirs: Optional[Sequence[str]] = None,
                      source_filter: Optional[SourceFilter] = None
                      ) -> Iterator[Tuple[Path, str]]:
    """Convenience generator over *source-suffix* files (excluded dirs skipped).

    Use :func:`scan_tree` when the exclusion trail matters; this helper is for
    callers that just want to iterate candidates.
    """
    flt = source_filter or SourceFilter()
    known = flt.known_suffixes()
    files, _excluded = scan_tree(root, flt, source_dirs)
    for path, rel in files:
        if Path(rel).suffix.lower() in known:
            yield path, rel


# --- shared file reading ---------------------------------------------------

DEFAULT_MAX_FILE_BYTES = 4 * 1024 * 1024


def read_source_lines(path, max_bytes: int = DEFAULT_MAX_FILE_BYTES,
                      ) -> Optional[List[str]]:
    """Read ``path`` as lines, or ``None`` when unreadable / over ``max_bytes``.

    ``None`` means "we could not read this", which the callers record as a
    ``skip_reason`` -- never as "the file has no content".
    """
    path = Path(path)
    try:
        if max_bytes and path.stat().st_size > max_bytes:
            return None
        return path.read_text(encoding="utf-8", errors="replace").splitlines()
    except OSError:
        return None
